//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStorage_v02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public long SizeBytes { get; set; }
        public System.DateTime DateOfAddition { get; set; }
        public System.DateTime DateOfRemoval { get; set; }
        public bool IsFavorite { get; set; }
        public bool IsRemoved { get; set; }
        public int UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
